services:
  9router:
    image: node:20-alpine
    container_name: 9router
    ports:
      - '20128:20128'
    volumes:
      - 9router-data:/app/data
    command: sh -c "npm install -g 9router@latest --prefer-online && 9router"
    restart: unless-stopped

volumes:
  9router-data:
